### ISSUE TITLE
Add option (popup window) to start stream (VOD) at certain time.

### ISSUE THREAD

**Issue by baizon** [IsSuEat/open-livestreamer-firefox-addon#10]
An popup window to start a VOD at a certain time would be a nice feature. It would require to ad an parameter to the url. Example:
Stream starting from the beginning: http://www.twitch.tv/exampleuser/b/621356598
Stream starting from a chosen time: http://www.twitch.tv/exampleuser/b/621356598?t=5h13m37s

**Comment by julianrichen** [comment]
`--player-passthrough=hls` allows for seeking in the video player, however passing it with a url that has the `?t=` parameter does not seem to launch it at that time.

Also for future reference:
https://github.com/chrippa/livestreamer/issues/711#issuecomment-102584123

>Twitch uses two different systems for VODs (one is flash based (the /b/ ones) and one is hls based (the /v/ ones)). Because Livestreamer does not support seeking for HLS the t parameter only works on URLs containing /b/.

**Comment by IsSuEat** [comment]
I don't really see any necessity for this, closing
