### ISSUE TITLE
Bookmarks (GUI) of favorite streams.

### ISSUE THREAD

**Issue by baizon** [IsSuEat/open-livestreamer-firefox-addon#13]
Hi,
I just had an great idea... :)
A bookmark-like list (add, edit, remove streams), that can be accessed through the Livestreamer button. That would allow to quickly access all favorite streams. So this would be a great 2.0 feature.

**Comment by IsSuEat** [comment]
Hi there!
I thought about that aswell, how would you like that implemented? right click on a menu button seems to be pretty hard to handle with the current addon-sdk (only looked briefly)

**Comment by baizon** [comment]
I thought of something like this...
![prototype](https://cloud.githubusercontent.com/assets/4971611/6237091/358bf9da-b6f0-11e4-9588-b1f3fa90c174.png)

**Comment by baizon** [comment]
I've made a mockup of the bookmark GUI. Any feedback would be good.
![mockup01](https://cloud.githubusercontent.com/assets/4971611/6251386/fd0da852-b793-11e4-87a0-bb13f83e650d.png)
![mockup02](https://cloud.githubusercontent.com/assets/4971611/6251392/01368e9e-b794-11e4-97cd-827848848b5c.png)

**Comment by baizon** [comment]
Just a quick question @IsSuEat, are you implementing some sort of bookmark gui?

**Comment by IsSuEat** [comment]
I don't think I will implement a fancy GUI like you are suggesting. What I was considering is to have normal bookmarks but being able to directly launch livestreamer on them.
