### ISSUE TITLE
Use github releases to host the XPI

### ISSUE THREAD

**Issue by nodiscc** [IsSuEat/open-livestreamer-firefox-addon#14]
Hi, this addon looks interesting, thanks for working on this. May I suggest that you use github's [releases](https://github.com/blog/1547-release-your-software) feature to host the XPI like we did at [RequestPolicyContinued](https://github.com/RequestPolicyContinued/requestpolicy/releases)? Git is [notoriously bad at managing binary files](https://robinwinslow.co.uk/2013/06/11/dont-ever-commit-binary-files-to-git/) and you'll end up with a repo that grows dramatically in size.

**Comment by baizon** [comment]
Indeed, I also made an issue on this topic (https://github.com/IsSuEat/open-livestreamer-firefox-addon/issues/12).

**Comment by IsSuEat** [comment]
Using this feature now. Hope I did it right ;) Didnt know about this to date

**Comment by nodiscc** [comment]
@IsSuEat Nice; you mostly got it right! You forgot to rename the `.xpi.zip` to `.xpi` though.

**Comment by baizon** [comment]
Also, the source code is 1.2 and not 1.2.1.

**Comment by IsSuEat** [comment]
@nodiscc github would not let me upload the xpi. Unrecognized file blah
