### ISSUE TITLE
Use youtube-dl as a backend?

### ISSUE THREAD

**Issue by nodiscc** [IsSuEat/open-livestreamer-firefox-addon#15]
Hi, I did not have the time to look at the source yet; Is there a possibility to add/set [youtube-dl](https://github.com/rg3/youtube-dl/) instead of livestreamer as a backend? Youtube-dl has support for more than [500 video hosting sites](https://github.com/rg3/youtube-dl/blob/master/docs/supportedsites.md). Stream support [has recently been added to youtube-dl](https://github.com/rg3/youtube-dl/issues/893), providing support for the same services as livestreamer.

I see in the screenshot of the prefs dialog that you can set the path to the livestreamer binary. Do you call this executable directly from the addon?

**Comment by baizon** [comment]
Yes, the executable is called directly using nsIProcess(https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XPCOM/Reference/Interface/nsIProcess).

**Comment by IsSuEat** [comment]
It is not currently possible in the addon, because I check for the name of the binary. Remove or enhance that check and it should work

**Comment by nodiscc** [comment]
XUL/XPCOM addons are deprecated, closing.
