### ISSUE TITLE
new feature

### ISSUE THREAD

**Issue by Alessandro-Barbieri** [IsSuEat/open-livestreamer-firefox-addon#19]
Add dailymotion support.

**Comment by baizon** [comment]
You mean games.dailymotion.com?

**Comment by Alessandro-Barbieri** [comment]
Yes.

**Comment by baizon** [comment]
Please notice, you also need Livestreamer v1.12.0 (https://github.com/chrippa/livestreamer/releases/tag/v1.12.0).

**Comment by IsSuEat** [comment]
Merged. Thanks for the PR baizon

**Comment by baizon** [comment]
Would it be possible to put 1.2.2 into [releases](https://github.com/IsSuEat/open-livestreamer-firefox-addon/releases) and also update it on [addons.mozilla.org](https://addons.mozilla.org/en-US/firefox/addon/open-livestreamer/)?
