### ISSUE TITLE
More resolution option

### ISSUE THREAD

**Issue by mrclza** [IsSuEat/open-livestreamer-firefox-addon#21]
There's six (audio, mobile (worst), low, medium, high and source (best)) resolutions to use with Livestream but in the plugin there's only Best (Source), Medium and Low.

Could you include these resolutions as well?

**Comment by IsSuEat** [comment]
You can specify a resolution in the addon settings. Here you can specify anything that livestreamer supports. But the three that are displayed in the popup dialog are the ones that work most of the time. These settings will be used when you open a stream via rightclick.
