### ISSUE TITLE
Feature suggestion: Hide livestreamer console window

### ISSUE THREAD

**Issue by elgonzo** [IsSuEat/open-livestreamer-firefox-addon#22]
Just a small feature suggestion. It is not something big, and addresses just a minor annoyance. Still... ;)

I am using Livestreamer in conjunction with MPC-HC, and when using your (very useful) plug-in, it always opens the Livestreamer console window.

It would be preferable to have an checkbox that enables/disables hiding of this Livestreamer console window. While i think that most users want to have the Livestreamer console hidden, such a checkbox as part of the plug-in options allows enabling of the Livestreamer console on demand when troubleshooting of streaming issues is necessary.

Anyway, your plug-in is great; i love especially the ability to start Livestreamer via context menu on a twitch stream link. Thank you!

**Comment by IsSuEat** [comment]
Hi there! What OS are you using? I presume you are on Windows? I will try to see if there is a possibility to stop that cmd promt from popping up.

**Comment by elgonzo** [comment]
Yupp. I use Win 7 x64 Pro, with current Firefox 37.0.1.

**Comment by IsSuEat** [comment]
It doesn't look like I can do much here. This is coming from livestreamer itself and not from the addon. 
What you could try doing is using a tool such as SilentCMD and wrapping the livestreamer executable with it. I don't have a Windows install at hand, so can't really try

**Comment by julianrichen** [comment]
A bat file could be used instead of livestreamer, apparently the following should work:
```bat
@echo off
:: save as live.bat in livestreamer folder
:: use it in the same way [Win+R]: live [url] [quality]
PUSHD %~dp0
echo On Error Resume Next> "%temp%\~1337run.vbs"
echo CreateObject("Wscript.Shell").Run "livestreamer "+WScript.Arguments(0)+" "+WScript.Arguments(1),0,False>> "%temp%\~1337run.vbs"
echo Err.Clear>> "%temp%\~1337run.vbs"
CALL CSCRIPT //nologo "%temp%\~1337run.vbs" %~1 %~2 &DEL /F /Q "%temp%\~1337run.vbs" &EXIT /B
:: provided by aveyo
```

Better then using a third-party binary.

[Source](http://www.reddit.com/r/Twitch/comments/2i7w3z/livestreamer_batch_file_to_hide_cmd_window/)
