### ISSUE TITLE
A possible Chrome version?

### ISSUE THREAD

**Issue by Galeonz** [IsSuEat/open-livestreamer-firefox-addon#23]
First of all, thanks for this extension, it makes everything easier!

I just would like to know if you plan to have a chrome version of this extension in the future.
It would be really cool, we kinda don't have anything similar for Chrome.

**Comment by IsSuEat** [comment]
Hi there! 
Thanks for the kind words.
I will look into what it would take, to port this to chrome. I can't give you any promises though :)

**Comment by IsSuEat** [comment]
I briefly looked into this, it might be possible with [native messaging](https://developer.chrome.com/extensions/nativeMessaging) 
I found a [chrome extension](http://codekiem.com/2014/08/29/quickstreamer-livestreamer-gui-for-google-chrome/) that is pretty similiar to this one here.
