### ISSUE TITLE
Add localizations

### ISSUE THREAD

**Issue by IsSuEat** [IsSuEat/open-livestreamer-firefox-addon#26]
Hi there!

Julian Richen added localization support, so we should use this! :)
I am currently adding a German translation, but that's about all the languages I can translate.
So if you want the addon in your language, please submit a PR 

Thanks, Armin

**Comment by julianrichen** [comment]
Reference:
https://developer.mozilla.org/en-US/Add-ons/SDK/Tutorials/l10n

For local codes:
https://wiki.mozilla.org/L10n:Locale_Codes

`<639-1 code>-<316601 code>.properties`

Use the 639-1 column: http://en.wikipedia.org/wiki/List_of_ISO_639-1_codes
Use the Alpha-2 code column: http://en.wikipedia.org/wiki/ISO_3166-1

Example file names:
```
en-US.properties
en-UK.properites
de-DE.properites
fr-FR.properties
```

I guess [en-US.properties](https://github.com/IsSuEat/open-livestreamer-firefox-addon/blob/master/locale/en-US.properties) should be the base template?

**Comment by IsSuEat** [comment]
Yes, I would also say that we use [en-US.properties](https://github.com/IsSuEat/open-livestreamer-firefox-addon/blob/master/locale/en-US.properties) as the template for any future translations.

What I couldn't find is a way to translate the addons description  string though. Might not be supported by the addon-sdk for the time being

**Comment by julianrichen** [comment]
I also had trouble finding this but stumbled across this:
https://developer.mozilla.org/en-US/docs/Mozilla/Localization/Localizing_extension_descriptions?redirectlocale=en-US&redirectslug=Localizing_extension_descriptions

It seems like you manually create the `install.rdf`?
https://developer.mozilla.org/en-US/Add-ons/Install_Manifests

Not 100% but my best guess would be:
```xml
<?xml version="1.0"?>

<RDF xmlns="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
     xmlns:em="http://www.mozilla.org/2004/em-rdf#">
  <Description about="urn:mozilla:install-manifest">
    <em:id>jid1-Y6BhyMM8GoZ3eA</em:id>
    <em:localized>
      <Description>
        <em:locale>en-US</em:locale>
        <em:name>Open in Livestreamer</em:name>
        <em:description>Open livestreamer directly from your browser</em:description>
      </Description>
    </em:localized>
    <em:localized>
      <Description>
        <em:locale>de-DE</em:locale>
        <em:name>Mit Livestreamer öffnen</em:name>
        <em:description>This is totally in German.</em:description>
      </Description>
    </em:localized>
</RDF>
```

> The file must be called install.rdf and live at the top level of an addon's XPI file.
So in the root?
