### ISSUE TITLE
Feature request: Crunchyroll support

### ISSUE THREAD

**Issue by ZachBacon** [IsSuEat/open-livestreamer-firefox-addon#28]
Just to throw out a suggestion, maybe a possibility of adding crunchyroll support. Albeit the end user will need to add his credentials before hand for their account, but it's a suggestion at least.

**Comment by julianrichen** [comment]
A friendly user interface would be a good, however, you can do the following atm:
1. CTRL + SHIFT + A
2. Select "Options" button under "Open Livestreamer"
3. Under "Optional arguments for livestreamer" add `--crunchyroll-username=xxxx --crunchyroll-password=xxx`

That command will be used every time you click the Open with Livestreamer button, so it's not a real solution :/

**Comment by DoctorWho11** [comment]
That much I already know, however I was thinking mainly because of how this extension works with youtube, right clicking on a video and then selection open with livestreamer. Currently that's unimplemented by the looks of things.
