### ISSUE TITLE
Improve Firefox addon settings usability

### ISSUE THREAD

**Issue by noodle-** [IsSuEat/open-livestreamer-firefox-addon#32]
"Select stream quality" dialog shows up every time, even when the stream quality option of the addon (the one in about:addons --> Extensions --> Livestreamer)  is set to "best".

As in,
As a user I want to set the quality to always be "best" so I can skip the "Select stream quality" dialog.

This used to work before the new major update.

**Comment by julianrichen** [comment]
Did you uncheck the "Quality selection menu" option?

**Comment by noodle-** [comment]
Oops.

Well then I'd suggest placing those two options closer to each other or (if it's possible) disabling the "Stream quality" option when the "Quality selection menu" option is set to enabled, so other people other stupid people, like me, won't make the same mistake.

That's just a tiny suggestion and not really an issue.

**Comment by IsSuEat** [comment]
I'm looking into this. Either really only show the quality box if the checkbox is ticked, or have the option presented in another way.

**Comment by julianrichen** [comment]
@IsSuEat Would a dropdown work?
* Show menu
* Best
* Worst

best & worst are the only options guaranteed to work on any stream on any site but users can't select site specific qualities.
![open-in-livestreamer-options](https://cloud.githubusercontent.com/assets/58045/8629906/dbe20286-272d-11e5-8b3b-dd1f188f076d.png)

Also I looked into showing more options if the checkbox is ticked but did not find anything. You might be able to with [preferences/service](https://developer.mozilla.org/en-US/Add-ons/SDK/Low-Level_APIs/preferences_service) but not 100% sure.
