### ISSUE TITLE
Move to jpm

### ISSUE THREAD

**Issue by julianrichen** [IsSuEat/open-livestreamer-firefox-addon#36]
As of Firefox 38 cfx has been replaced by jpm, a node.js replacement. jpm changes the folder structure a bit (ex. lib/main.js has moved to /index.js) and a few other things. Not an urgent issue but might be worth transitioning to it.

Moving from cfx to jpm:
https://developer.mozilla.org/en-US/Add-ons/SDK/Tools/cfx_to_jpm

**Comment by IsSuEat** [comment]
Good to know, will try that out and use it for the next release. I never really did anything with node.js so let's see how that goes :P

**Comment by julianrichen** [comment]
I also never used node.js & npm before but it was surprising easy! jpm can also be install with npm globally (`npm install jpm -g`) so you can use jpm in any directory. No longer need to have the firefox sdk with your project in it :D

I did have one problem on Debian/Linux where jpm could not find the firefox binary because instead of looking for `/usr/bin/firefox` it went to /usr/lib/firefox` & `/usr/lib64/firefox`.... It should be fix in version 1.0.0 but the issue still exist (in fx-runner).

Adding a simple alias in .bashrc fixed it:
```bash
alias jpm="jpm -b /usr/bin/firefox"
```
