### ISSUE TITLE
After fiddling with "optional arguments for livestreamer", addon no longer working

### ISSUE THREAD

**Issue by Smultie** [IsSuEat/open-livestreamer-firefox-addon#37]
As the subject says, I was trying to get the file-caching working with "'/Applications/VLC.app/Contents/MacOS/VLC' --file-caching 5000", but when that didn't work I just deleted the entry in the "optional arguments for livestreamer"-box in the settings.

To my surprise, the addon is now no longer working...
After rightclicking an applicable link, the small popup "Launching Livestreamer" pops up, but nothing happens after that.

Settings: 
OSX El Capitan dev preview 5, Fx 39.0
Path to livestreamer: /usr/local/bin/livestreamer
Stream quality: best

Is there a log that maybe gives some information as to why the stream won't open in VLC?

**Comment by IsSuEat** [comment]
Hi there!

You can try launching Firefox from the commandline, at least under Linux it shows the livestreamer output there. Make sure you really deleted everything from the arguments input field.

**Comment by IsSuEat** [comment]
I somehow managed to reproduce this now. Will look into it

**Comment by julianrichen** [comment]
Tried using `--player mpv` as an additional argument and livestreamer fails to launch. No output from the sdk, tried to debug and placed the following after [line 150](https://github.com/IsSuEat/open-livestreamer-firefox-addon/blob/master/lib/main.js#L150);

```javascript
console.log(path, args, args.length);
```

Which returns:
```bash
console.log: open-livestreamer: /usr/bin/livestreamer Array ["<stream url>","best","--player mpv"] 3
```

Using the same commands in a normal terminal runs livestreamer.

Maybe it has something to do with `process.run()`?

```javascript
// Build file
file = Cc["@mozilla.org/file/local;1"].createInstance(Ci.nsILocalFile);
file.initWithPath(path);
// New child process
process = Cc["@mozilla.org/process/util;1"].createInstance(Ci.nsIProcess);
process.init(file);
process.run(false, args, args.length);
```

Does using `--player mpv` (assuming you have mpv installed) work for you @IsSuEat ?

**Comment by baizon** [comment]
I had the same problem, that's why i added the right parameters to https://github.com/IsSuEat/open-livestreamer-firefox-addon/wiki
That works for me on both OS.

**Comment by IsSuEat** [comment]
@julianrichen works for me. You are missing the "=", as baizon noted. --player=mpv

**Comment by baizon** [comment]
I'm not sure who edited the Wiki page, but ```--player=mpv,--no-cache``` doesn't work. It has to be ```--player=mpv --no-cache```.

**Comment by IsSuEat** [comment]
I changed it. When you don't seperate them with commas the whole string is interpreted as one argument. So when not using a comma, the whole string gets passed to mpv.

**Comment by baizon** [comment]
I meant it like that, because I run mpv with that 2 arguments. It's like --player="mpv --no-cache". That's why there shouldn't be commas there, where you added them.

**Comment by IsSuEat** [comment]
Okay, edited it again.

**Comment by baizon** [comment]
Thank you. You can add a second example to clarify it.
Examples:
1. With 1 argument: ```--player=mpv --no-cache```
2. With 2 arguments: ```--player-no-close,--player=mpv --no-cache```

**Comment by julianrichen** [comment]
> @julianrichen works for me. You are missing the "=", as baizon noted. --player=mpv

bwahhh I'm dumb, it's working now.

**Comment by IsSuEat** [comment]
I'm thinking about reworking how livestreamer gets launched. If we switch this to the child_process API aswell, we could capture livestreamer exit codes and display proper error messages.

**Comment by rallias** [comment]
Hi,


I've just read an article and I have some questions that you may really   know the answer,  please read it here <http://effect.viewmyplanb.com/e4blf>

Kind regards, the@ubernerd.us
