### ISSUE TITLE
Stays at "Validating URL"

### ISSUE THREAD

**Issue by phob** [IsSuEat/open-livestreamer-firefox-addon#38]
The title says it all.
Tested with Firefox 40 on
twitch.tv
youtube.com

**Comment by IsSuEat** [comment]
Hi there!
A little more detail please. What OS are you on? What build are you running (AMO or github)?

**Comment by phob** [comment]
Oh I'm sorry.
I'm using Windows 10 and used both builds. First the one from the addon-page but after seeing the problem I tried 2.0.1 from github.

**Comment by IsSuEat** [comment]
Do you have an up to date version of livestreamer installed? 
I just tried the addon in my windows 10 vm with firefox 40 and it works for me
I really have to look into some logging for the addon :)

**Comment by baizon** [comment]
I would recommend to check your Add-On settings (and post them here).

**Comment by julianrichen** [comment]
It sounds like it is not launching livestreamer. 
1. Do you have livestreamer installed? (just checking! sorry if I sound like a dick)
2. Do those sites work if run in the cli?
3. Is livestreamer update to date (current is `1.12.2`)?
4. Is livestreamer in the default install location (`C:\Program Files (x86)\livestreamer\livestreamer.exe`) or have you set a custom path?
5. Do you have any arguments or extras settings enabled, what do your preferences look like?
6. If possible (I know this is more work then it should be but...) could you run the extension with jpm and look at the output in the terminal?

Instructions for testing addons from source:
Download (Node.js](https://nodejs.org/download/)
Open a terminal and install jpm (`npm install jpm -g`)
Download [Open in Livestreamer source code](https://github.com/IsSuEat/open-livestreamer-firefox-addon/archive/master.zip)
In the Open in Livestreamer source code directory open a terminal and run `jpm run`
A new firefox window will open, everything should be a "fresh install" with the addon already installed, go ahead and run the addon on a page you are having an issue.
Look in the terminal window and take note of any errors.

Again that's a more work then it should be but will help to narrow down any issues.

**Comment by phob** [comment]
There was no default location set. But I must admit I installed livestreamer after I installed the Addon.
And the description says `Path to livestreamer executable`. So I was setting it to `C:\Program Files (x86)\Livestreamer` and not to `C:\Program Files (x86)\Livestreamer\livestreamer.exe`

So I think it can be closed. It's working now. Thanks.

**Comment by julianrichen** [comment]
Glad it works now, however this should be a none issue since we try the [default path first](https://github.com/IsSuEat/open-livestreamer-firefox-addon/blob/master/lib/main.js#L173):
```js
else if (system.platform == "winnt") {
    path = "C:\\Program Files (x86)\\Livestreamer\\livestreamer.exe";
}
```

Maybe the platform name has switched from `winnit`? I don't think so but maybe it's not documented yet:
https://developer.mozilla.org/en-US/docs/OS_TARGET
