### ISSUE TITLE
Doesn't seem to work under Linux

### ISSUE THREAD

**Issue by fthiesse** [IsSuEat/open-livestreamer-firefox-addon#39]
Once I click "Launch link url in livestreamer" is says "livestreamer.exe not in PATH". So that .exe seems to indicate it's for windows only.

livestreamer is part of my linux path environment, as I can start it from anywhere by just typing "livestreamer" in a console.

**Comment by julianrichen** [comment]
Is your livestreamer located in `/usr/bin/livestreamer`? That is the path it checks first. If you have it in another path you should change the "Path to Livestreamer" in the addons options (`CTRL + A` -> Extensions -> Open Livestreamer).

That is strange that it's reporting livestreamer.exe, might be a bug.

**Comment by fthiesse** [comment]
My bad, there are actually two (or more) livestreamer firefox addons. I must have mixed them up as thisone works.
