### ISSUE TITLE
Change URL check from adressbar to "link to click".

### ISSUE THREAD

**Issue by baizon** [IsSuEat/open-livestreamer-firefox-addon#4]
Hi,
if it is possible, please change the URL check, so that if I'm on a 3rd party website it is still possible to have the option "Open with livestreamer". I always have to go to twitch.tv/hitbox.tv/etc., so that the menu entry appears. It would be awesome, if it also worked on other sites.

**Comment by armathriosh** [comment]
Also would love to see that feature implemented..

**Comment by baizon** [comment]
I'm on it, will make a pull request with this feature asap.

**Comment by armathriosh** [comment]
cool, good to know :)

**Comment by baizon** [comment]
Almost done.
Just one problem... on hitbox.tv, clicking on the image doesn't work, because it is a different node type. So it has to be clicked on the url on the image (see attachment). 
If this is not a problem i the code is done and i can make a pull request. Else i have to take a deeper look at it which can take much longer. So if you guys are good to go i will make the pull request.
![link](https://cloud.githubusercontent.com/assets/4971611/6198988/b022d510-b425-11e4-8b4d-1bb3f64dd198.png)

**Comment by baizon** [comment]
I've made a pull request.
Also found a little bug, that opening twitch.tv vods which have a timestamp aren't working yet.

**Comment by baizon** [comment]
OK, got it working now. Will make another pull request.

**Comment by IsSuEat** [comment]
Thanks for the PR, but why didnt you just use PredicateContext as you suggested at first? I just pushed a version with that in place. Also I think matching the URL that exact is overhead. 
But I am open to talk about everything :)

**Comment by baizon** [comment]
Hi, just tested your new version.
IMHO with your version there are many false positives, for example all links on twitch can be opened.
My suggestion would be to just replace <code>var valid_urls = ["twitch.tv", "hitbox.tv", "youtube"];</code> with my regex:  
<code>currentUrl.match(/^http(s)?:\/\/(\w+\.)*twitch.tv\/[A-Za-z0-9 _-]+(\/[a-z]+\/[0-9]+(\?t=([0-9]+h)?([0-9]+m)?([0-9]+s)?)?)?$/i))</code>
 <code>currentUrl.match(/^http(s)?:\/\/(\w+\.)*hitbox.tv\/[A-Za-z0-9 _-]+(\/video\/[0-9]+)?$/i)</code>
 <code>currentUrl.match(/^http(s)?:\/\/www.youtube.com\/watch\?v=[A-Za-z0-9 _-]+$/i)</code>

**Comment by IsSuEat** [comment]
That is absolutly true. But the thing is, either make a regex for every site and have to update them when something changes, or just add the site string.

**Comment by baizon** [comment]
I just tested your version with my regex and everything is working fine, with both the context menu, and the button.
The regex should also work with most changes. Take a look at the pull request.
