### ISSUE TITLE
Feature request: recent open

### ISSUE THREAD

**Issue by jonibi** [IsSuEat/open-livestreamer-firefox-addon#40]
Add next to the icon a drop down that shows a list with previously 10-15 opened streams. Click on one item and directly open the stream. I would really like such a feature because most of us watch the same streams

**Comment by IsSuEat** [comment]
Sorry, this is out of the scope of this addon. There are several stand alone livestreamer applications that provide history and other features:
https://github.com/chrippa/livestreamer/wiki/Alternative-interfaces
