### ISSUE TITLE
Stuck on "Launching Livestreamer" when using mpv on OS X

### ISSUE THREAD

**Issue by bramcordie** [IsSuEat/open-livestreamer-firefox-addon#49]
On OS X I can't use _livestreamer_ from the browser to launch _mpv_ without specifying the full path to the player. I first tried to configure livestreamer to use _mpv_ in the `.livestreamerrc` config file but then the add-on gets stuck on __Launching Livestreamer__. Using livestreamer from the CLI, with the same default config, does launch _mpv_ without a problem.

When I used the linux example arguments from the wiki the add-on was again stuck on __Launching Livestreamer__. Here the argument that specifies the player just says _mpv_ like you would expect.

I'm not sure if this is a quirk in the add-on or if livestreamer itself is to blame. I'm guessing the former because launching from the CLI works fine.

I ended up pointing livestreamer to the bin path in optional arguments of the add-on config. This resolves the problem. My config has been added to the wiki as an example:

> * OS X (_livestreamer_ and _mpv_ installed using [Homebrew]):  
> _Path to livestreamer_ `/usr/local/bin/livestreamer`  
> _Stream quality_ `best`  
> _Optional arguments for livestreamer_ `--player=/usr/local/bin/mpv --no-cache`

**Comment by IsSuEat** [comment]
Yup, this is known. The problem here is, afair, that the environment variables don't get resolved, thus your $PATH variable is probably empty. I don't really know if there is a workaround for this, so for the time being the full path must be specified
