### ISSUE TITLE
Plugin unable to detect streams on Afreecatv.com

### ISSUE THREAD

**Issue by RhysJB** [IsSuEat/open-livestreamer-firefox-addon#52]
Plugin unable to detect streams on Afreecatv.com since April27 Afreeca update. Is there any workaround?

**Comment by julianrichen** [comment]
open-in-livestreamer directly launches livestreamer so it's more than likely an issue upstream. In fact you already [reported a bug about it](https://github.com/chrippa/livestreamer/issues/1303). Nothing can be done here.
