### ISSUE TITLE
Migrate to WebExtensions

### ISSUE THREAD

**Issue by julianrichen** [IsSuEat/open-livestreamer-firefox-addon#53]
As of Firefox 48 Mozilla recommends moving to WebExtension. This is the future of extensions and allows for easier cross-browser extensions as chrome also supports this. News:
https://blog.mozilla.org/addons/2016/04/29/webextensions-in-firefox-48/

> With the release of Firefox 48, we feel WebExtensions are in a stable state. **We recommend developers start to use the WebExtensions API** for their add-on development.

Documentation:
https://developer.mozilla.org/en-US/Add-ons/WebExtensions

Get started, WebExtension no longer uses `jpm` but instead `web-ext`:

``` bash
npm update --global
npm install --global web-ext
web-ext --version
```

You can then add the addon locally via `about:debugging` which will also allows reloading without restarting a Firefox instance.

Or using `web-ext`:

```
web-ext run --source-dir=/path/to/my/extension
```

Or set it as a variable:

```
WEB_EXT_SOURCE_DIR=/path/to/my/extension
web-ext run
```

It seems that a lot has changed not only in the sdk but file layout, ideology (new security measures) and more:
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Your_first_WebExtension

~~Not even sure we can launch livestreamer but I assume it's possible. Going to investigate next week.~~
What a surprise, you need [NativeMessaging](https://developer.chrome.com/extensions/nativeMessaging) and Firefox [does not support it](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Chrome_incompatibilities#permissions) -_-

We can follow the [bug report](https://bugzilla.mozilla.org/show_bug.cgi?id=1190682) and hope they implement it soon. In the meantime we can work on porting everything else, maybe even get a switch for Native Messaging and make it work in chrome so when it becomes active we can just make it a default for Firefox.

Other resources:
- [Examples from mdn](https://github.com/mdn/webextensions-examples)
- [runtime.OS](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/runtime/PlatformOs)
- [List of supported functions](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Browser_support_for_JavaScript_APIs)
- [Native Messaging Firefox wiki](https://wiki.mozilla.org/WebExtensions/Native_Messaging)
- [Native Messaging Chrome wiki](https://developer.chrome.com/extensions/nativeMessaging)

**Comment by julianrichen** [comment]
`runtime.connectNative()` support coming in Firefox 50.0:
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/Runtime/connectNative

**Comment by julianrichen** [comment]
I have yet to try it my self but Firerfox 50.0 is now stable and should support `runtime.connectNative()`.

Usage:
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Native_messaging#Exchanging_messages

Sending the the command to streamlink/livestreamer/youtube-dl:
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/runtime/sendNativeMessage

The app manifest must be installed along side the app, so we would probably need a [first-run splash screen](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/runtime/onInstalled) explaining to the user how to download & install streamlink then install the app manifest.

We might be able to use HTML5's filesystem api to "Install" the app manifest easily using the first-launched idea:
https://www.html5rocks.com/en/tutorials/file/filesystem/

**Windows**

```
REG ADD "HKEY_CURRENT_USER\SOFTWARE\Mozilla\NativeMessagingHosts\<name>" /ve /d "C:\path\to\<name>.json" /f
```

**Mac OS X**
Global:

```
/Library/Application Support/Mozilla/NativeMessagingHosts/<name>.json
```

Per-user:

```
~/Library/Application Support/Mozilla/NativeMessagingHosts/<name>.json
```

**Linux**
Global:

```
/usr/lib/mozilla/native-messaging-hosts/<name>.json
/usr/lib64/mozilla/native-messaging-hosts/<name>.json
/usr/share/mozilla/native-messaging-hosts/<name>.json
```

Per-user

```
~/.mozilla/native-messaging-hosts/<name>.json
```

## Launch files

Will pass all arguments we send into the app

Windows
64bit:

``` bat
@echo off

start /B "%programfiles%\Streamlink\bin\" streamlink.exe %*
```

32bit:

``` bat
@echo off

start /B "%programfiles(x86)%\Streamlink\bin\" streamlink.exe %*
```

Auto detect

``` bat
@echo off

IF EXIST "%programfiles%\Streamlink\bin\streamlink.exe" (
    start /B "%programfiles%\Streamlink\bin\" streamlink.exe %*
) ELSE IF EXIST "%programfiles(x86)%\Streamlink\bin\streamlink.exe" (
    start /B "%programfiles(x86)%\Streamlink\bin\" streamlink.exe %*
) ELSE (
    echo Error
)
```

Linux

``` bash
#!/bin/sh
streamlink "$@"
```

We would also create one for livestreamer and youtube-dl, so users can switch between them.

**Comment by xxxxxxccccccccccc** [comment]
Seems how to do it is all figured out. I understand a separate program is needed to make it work, which would render the old/current version nonworking (without the extra program). 

Given this, what's the plan here? Is an entirely new extension going to be made... ?

**Comment by IsSuEat** [comment]
As I started using firefox again (FF57 <3), I will try to update this addon again to be compatible with the newest firefox and adopt the code to  support streamlink.
But I think I will have to look at how javascript works nowadays, have not used any JS since I wrote this addon :D

**Comment by IsSuEat** [comment]
This has gotten way more inconvenient with the deprecation of XUL imho. I ended up writing a python script which transforms the messages it receives to STDIN from the addon into streamlink arguments.
I am not sure yet, how to handle the installation of this script, and whether python is a good choice of language, because I don't think its a default on windows. 

what I forgot: a benefit of using python might be that we could actually directly use the streamlink api, and not execute the streamlink binary in a sub shell
