### ISSUE TITLE
Option to hide menu item?

### ISSUE THREAD

**Issue by WcDuck** [IsSuEat/open-livestreamer-firefox-addon#54]
Is it possible to add the option to hide the menu item? It's locked in Menu Wizard so I can't remove it with that either.

**Comment by IsSuEat** [comment]
Which menu item do you mean?

**Comment by WcDuck** [comment]
Sorry, I meant the right click menu item. http://i.imgur.com/j1DNolu.png

**Comment by IsSuEat** [comment]
The next version will have a checkbox to toggle the context menu entry
