### ISSUE TITLE
Does not work unless I launch Firefox as Administrator

### ISSUE THREAD

**Issue by deadman3000** [IsSuEat/open-livestreamer-firefox-addon#56]
If I try to launch a Youtube video in Firefox I get a CMD window open briefly but it complains about error message 740 and requiring elevated privileges. The only way I can get it to work is to run Firefox with elevated Administrator privileges which might be dangerous (and also stops my Logitech back/forwards mouse buttons from working for some reason).

Any idea?

**Comment by IsSuEat** [comment]
Could you resolve this problem?
