### ISSUE TITLE
StreamLink, Youtube and 1080p

### ISSUE THREAD

**Issue by SeNeO** [IsSuEat/open-livestreamer-firefox-addon#61]
I've just made the switch to streamlink to replace livestreamer.
Streamlink is now able to use 1080p stream for youtube, but it doesn't seems to work with this addon. Setting 1080p for the stream quality settings the stream doesn't play, and the 1080p stream is not shown when using the quality selection menu.

Is there someting I'm doing wrong?

**Comment by Shaaah** [comment]
I tried to reproduce, but everything works okay for me.

With "Quality selection" checked, I can see the 1080p option

With "Quality selection" unchecked, and "1080p" or "best" in "Stream Quality" I still get the 1080p video.

>Is there something I'm doing wrong?

The "Path to livestreamer" Option should look something like this : "C:\Program Files (x86)\Streamlink\bin\streamlink.exe"

**Comment by SeNeO** [comment]
Since my post, I have found I only have issues with videos from my 'watch later' list. Which have the following format : https://www.youtube.com/watch?v=XXXXXXX&list=WL&index=4. The issue is with the "&list=WL&index=4" part of the url, if I remove it and directly use streamlink it works fine. I'm not sur if the issue is with your addon or with streamlink.

**Comment by Shaaah** [comment]
I'm just a random dude, I'm not developping this, I'm just watching the project :)

I tried multiple things with youtube playlists and I still can't reproduce your issue ... I'm out of ideas about what is going wrong with the addon.

Anyway here's the versions I'm using 
>Open Livestreamer 2.0.3
>streamlink 0.6.0 
>Firefox 53.0.3 (32 bits)
